// Re-export all types from core (DRY - zero duplication)

// Type exports
export type {
  ApiErrorCode,
  ApiErrorResponse,
  ApiErrorShape,
  ApiMeta,
  ChatCompletion,
  ChatCompletionChunk,
  ChatCompletionCreateParams,
  ChatCompletionMessage,
  ChatCompletionMessageParam,
  GenerationConfig,
  HeartbeatResult,
  HubConfig,
  InputItemListParams,
  LlmMetrics,
  MachineSpecs,
  Model,
  ModelDeleted,
  NetworkConfig,
  OllamaConfig,
  ParticipantAuthHeaders,
  ParticipantCapabilities,
  ParticipantConnection,
  ParticipantInfo,
  ParticipantInfoInternal,
  ParticipantRegistration,
  ParticipantStatus,
  ParticipantSummary,
  Response,
  ResponseCreateParams,
  ResponseCreateParamsNonStreaming,
  ResponseCreateParamsStreaming,
  ResponseInputItem,
  ResponseItemList,
  ResponseRetrieveParams,
  ResponseRetrieveParamsNonStreaming,
  ResponseRetrieveParamsStreaming,
  ResponseStreamEvent,
  ResponseUsage,
  RoomEvent,
  RoomEventType,
  RoomInfo,
  RoomInfoPublic,
  RoomSummary,
  RuntimeConfig,
  RuntimeConfigPublic,
  TunnelBootstrap,
} from "@gambi/core/types";
// Re-export Zod schemas for runtime validation (with Schema suffix to avoid conflicts)
// Re-export constants
export {
  ApiErrorCode as ApiErrorCodeSchema,
  ApiErrorResponse as ApiErrorResponseSchema,
  ApiErrorShape as ApiErrorShapeSchema,
  ApiMeta as ApiMetaSchema,
  GenerationConfig as GenerationConfigSchema,
  HEALTH_CHECK_INTERVAL,
  HeartbeatResult as HeartbeatResultSchema,
  HubConfig as HubConfigSchema,
  LlmMetrics as LlmMetricsSchema,
  MachineSpecs as MachineSpecsSchema,
  NetworkConfig as NetworkConfigSchema,
  OllamaConfig as OllamaConfigSchema,
  PARTICIPANT_TIMEOUT,
  ParticipantAuthHeaders as ParticipantAuthHeadersSchema,
  ParticipantConnection as ParticipantConnectionSchema,
  ParticipantInfo as ParticipantInfoSchema,
  ParticipantInfoInternal as ParticipantInfoInternalSchema,
  ParticipantRegistration as ParticipantRegistrationSchema,
  ParticipantStatus as ParticipantStatusSchema,
  ParticipantSummary as ParticipantSummarySchema,
  RoomEvent as RoomEventSchema,
  RoomEventType as RoomEventTypeSchema,
  RoomInfoInternal as RoomInfoSchema,
  RoomInfoPublic as RoomInfoPublicSchema,
  RoomSummary as RoomSummarySchema,
  RuntimeConfig as RuntimeConfigSchema,
  RuntimeConfigPublic as RuntimeConfigPublicSchema,
  TunnelBootstrap as TunnelBootstrapSchema,
} from "@gambi/core/types";
