// Re-export all types from core (DRY - zero duplication)

// Type exports
export type {
  ApiErrorCode,
  ApiErrorResponse,
  ApiErrorShape,
  ApiMeta,
  ChatCompletion,
  ChatCompletionChunk,
  ChatCompletionCreateParams,
  ChatCompletionMessage,
  ChatCompletionMessageParam,
  GenerationConfig,
  HubConfig,
  HeartbeatResult,
  InputItemListParams,
  LlmMetrics,
  MachineSpecs,
  Model,
  ModelDeleted,
  NetworkConfig,
  OllamaConfig,
  ParticipantAuthHeaders,
  ParticipantCapabilities,
  ParticipantInfo,
  ParticipantInfoInternal,
  ParticipantRegistration,
  ParticipantSummary,
  ParticipantStatus,
  RoomEvent,
  RoomEventType,
  Response,
  ResponseCreateParams,
  ResponseCreateParamsNonStreaming,
  ResponseCreateParamsStreaming,
  ResponseInputItem,
  ResponseItemList,
  ResponseRetrieveParams,
  ResponseRetrieveParamsNonStreaming,
  ResponseRetrieveParamsStreaming,
  ResponseStreamEvent,
  ResponseUsage,
  RoomInfo,
  RoomInfoPublic,
  RoomSummary,
  RuntimeConfig,
  RuntimeConfigPublic,
} from "@gambi/core/types";
// Re-export Zod schemas for runtime validation (with Schema suffix to avoid conflicts)
// Re-export constants
export {
  ApiErrorCode as ApiErrorCodeSchema,
  ApiErrorResponse as ApiErrorResponseSchema,
  ApiErrorShape as ApiErrorShapeSchema,
  ApiMeta as ApiMetaSchema,
  GenerationConfig as GenerationConfigSchema,
  HEALTH_CHECK_INTERVAL,
  HubConfig as HubConfigSchema,
  HeartbeatResult as HeartbeatResultSchema,
  LlmMetrics as LlmMetricsSchema,
  MachineSpecs as MachineSpecsSchema,
  NetworkConfig as NetworkConfigSchema,
  OllamaConfig as OllamaConfigSchema,
  PARTICIPANT_TIMEOUT,
  ParticipantAuthHeaders as ParticipantAuthHeadersSchema,
  ParticipantInfo as ParticipantInfoSchema,
  ParticipantInfoInternal as ParticipantInfoInternalSchema,
  ParticipantRegistration as ParticipantRegistrationSchema,
  ParticipantSummary as ParticipantSummarySchema,
  ParticipantStatus as ParticipantStatusSchema,
  RoomEvent as RoomEventSchema,
  RoomEventType as RoomEventTypeSchema,
  RoomInfoInternal as RoomInfoSchema,
  RoomInfoPublic as RoomInfoPublicSchema,
  RoomSummary as RoomSummarySchema,
  RuntimeConfig as RuntimeConfigSchema,
  RuntimeConfigPublic as RuntimeConfigPublicSchema,
} from "@gambi/core/types";
